### ISSUE TITLE
Add support of Watch only account

### ISSUE THREAD

**Issue by ArtemZinkov** [horizontalsystems/BitcoinCore.Swift#16]
As of now - .bip32 mentioned in BitcoinKit readme for watch only accounts - is skipped in build phase of bitcoinCore.
It is not clear - should it be .bip32, which is not handled (as shown on screenshot), or it is not necessary, thus making readme file for bitcoinKit - outdated.

<img width="1013" alt="Screenshot 2023-08-07 at 13 10 04" src="https://github.com/horizontalsystems/BitcoinCore.Swift/assets/34108556/6601b781-9d97-4da6-af93-8ae3f1f9405c">

**Comment by ArtemZinkov** [comment]
Tested on this piece of code.
For `zprv` (bip84) - it's downloading transactions, but not recognising old transactions.
For `xprv` (bip32) - it doesn't download transactions at all.

<img width="497" alt="image" src="https://github.com/horizontalsystems/BitcoinCore.Swift/assets/34108556/93a7b88d-db35-48c8-8247-69014c4ec26b">

**Comment by ArtemZinkov** [comment]
Same `seedData` used to initialise `bitcoinKit` works as expected

<img width="342" alt="image" src="https://github.com/horizontalsystems/BitcoinCore.Swift/assets/34108556/f1e198f9-af71-4be8-930b-e5b063c9c90a">

**Comment by ArtemZinkov** [comment]
All tested on .testNet .newWallet

**Comment by esen** [comment]
hey @ArtemZinkov ,

**.newWallet** is considered to sync transactions only after the last checkpoint block. It assumes that the wallet is new and it has no transactions. You can check with ".api" or ".full" to sync historical transactions.

**full**                           // Sync from bip44Checkpoint. Api restore disabled
**api**                           // Sync from lastCheckpoint. Api restore enabled
**newWallet**               // Sync from lastCheckpoint. Api restore enabled

_lastCheckpoint_ is the last block of the last difficulty adjustment and it's updated before each release of the app.

**Comment by ArtemZinkov** [comment]
Hello @esen thank you for answering!

I tried to generate pubKey the way you mentioned, but for some reason - old transactions was still not recognised as "ours"
<img width="907" alt="Screenshot 2023-08-08 at 15 10 13" src="https://github.com/horizontalsystems/BitcoinCore.Swift/assets/34108556/5c7fde73-e0b7-49bd-a68b-c3735f72e767">

BUT if i init wallet with Seed - it fetch and see transactions properly
<img width="377" alt="Screenshot 2023-08-08 at 15 11 53" src="https://github.com/horizontalsystems/BitcoinCore.Swift/assets/34108556/340f343c-f5f7-4ff6-8549-b2b77d401375">


For more context - i still use .newWallet, due to it's testNet, transactions in it is quite recent and they're shown in history, for seed initialisation.
I clear Tx (BitcoinKit.Kit.clear()) every time when i change init version (with seed, or derived pubKey), to replicate initial launch.

Sorry if i missing some important detail, please ask if some more context is required here

**Comment by ArtemZinkov** [comment]
Hello @esen i would really appreciate any help or suggestion here, due to i faced road block here and not sure where to move forward, to enable watch only mode for wallets.

i also checked syncMode == .full, and still had no history for watch only mode, while bitcoinKit with seedData initialiser was capable to see old transactions for wallet i used

**Comment by ArtemZinkov** [comment]
UPDATE:

Found what was the issue! 
Derived path ("m/84'/0'/0'") you provided - consists of:
Purpose - 84
coinType - 0 (bitcoin)
chain - 0

I was testing this all on testNet, thus coinType should be 1 as mentioned [here](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

i changed derivation path from "m/84'/0'/0'" to "m/84'/1'/0'" and it worked!
Thanks!!

**Comment by ArtemZinkov** [comment]
I would suggest to add this as a check to compare with networkType, during initialisation of bitcoinKit
